name: Push to cachix
on:
  push:
    branches:
      - main

jobs:
  cachix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v23
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: willruggiano
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: nix flake show --json | jq '.packages."x86_64-linux" | keys[]' | xargs -I {} nix build .#{} --accept-flake-config
      - run: cachix pin vscode-js-debug ${{ github.ref_name }} "$(nix build .#latest --accept-flake-config --print-out-paths)"
