name: Update sources
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-sources:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
      - uses: cachix/install-nix-action@v23
      - env:
          GH_TOKEN: ${{ github.token }}
        run: nix run .#update-sources
      - name: push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'willruggiano@users.noreply.github.com'
          git commit -am 'chore: update sources' || exit 0
          git push
